### ISSUE TITLE
Install problem with gdmodule dependencies in conda environment

### ISSUE THREAD

**Issue by houy10** [bunop/isoSegmenter#6]
Followed the `install.md` and got this error in `isoSegmenter.py --help`:
```
Traceback (most recent call last):
  File "/Users/houy10/miniconda3/envs/py27/bin/isoSegmenter.py", line 45, in <module>
    from GClib import constants, Graphs, Elements, Utility
  File "/Users/houy10/miniconda3/envs/py27/lib/python2.7/site-packages/GClib/__init__.py", line 47, in <module>
    import Graphs
  File "/Users/houy10/miniconda3/envs/py27/lib/python2.7/site-packages/GClib/Graphs.py", line 39, in <module>
    import gd
  File "/Users/houy10/miniconda3/envs/py27/lib/python2.7/site-packages/gd.py", line 11, in <module>
    import _gd
ImportError: dlopen(/Users/houy10/miniconda3/envs/py27/lib/python2.7/site-packages/_gd.so, 2): Symbol not found: _gdImageCreateFromPng
  Referenced from: /Users/houy10/miniconda3/envs/py27/lib/python2.7/site-packages/_gd.so
  Expected in: flat namespace
 in /Users/houy10/miniconda3/envs/py27/lib/python2.7/site-packages/_gd.so
 ```
 Thanks!

**Comment by bunop** [comment]
Dear @houy10 ,

It seems that your problem is related to the installation of `libgd` (dependency of `gdmodule`) in your conda environment, not to `isoSegmenter` itself. `gdmodule` by the way is not a conda package in *default* nor *conda-forge* channels. How do you have installed dependencies?  Please provide your [conda environment file](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-the-environment-yml-file). 

I think that the issue could be in the compiled `libgd` library in your conda environment. Maybe the simplest solution is to install `gdmodule` dependencies system-wide and then install in your conda environment only the required packages. Another solution could be using the docker image, this project is quite old and `gdmodule` was never [ported to python 3](https://github.com/Solomoriah/gdmodule/issues/3)

If you require to install `isoSegmenter` and its dependencies in a conda environment, you could try to import this environment (is compressed, GitHub doesn't allow to attach plain-text files):

[environment.yml.gz](https://github.com/bunop/isoSegmenter/files/7362644/environment.yml.gz)

Simply unpack `environment.yml.gz`, then create a new fresh environment using:

```
$ conda env create -f environment.yml --name isosegmenter
```

You don't need to modify anything in the environment file, conda detects your conda installation directory and will place the environment in the right place. Simply launch `isoSegmenter.py --help` after activating *isosegmenter* environment and see if you have any problem.

Hope this helps

**Comment by houy10** [comment]
Thank you so much @bunop. Here is what's in my enviroment.ymal:
```
dependencies:
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports_abc=0.5=py_1
  - biopython=1.68=py27_0
  - ca-certificates=2020.10.14=0
  - certifi=2019.11.28=py27_0
  - cycler=0.10.0=py27hfc73c78_0
  - expat=2.2.10=hb1e8313_2
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.10.4=ha233b18_0
  - functools32=3.2.3.2=py27_1
  - futures=3.3.0=py27_0
  - giflib=5.1.4=h1de35cc_1
  - icu=58.2=h0a44026_3
  - jpeg=9b=he5867d9_2
  - kiwisolver=1.1.0=py27h0a44026_0
  - libblas=3.9.0=12_osx64_openblas
  - libcblas=3.9.0=12_osx64_openblas
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgd=2.2.5=h9bbc9bf_3
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - - libiconv=1.16=h1de35cc_0
  - liblapack=3.9.0=12_osx64_openblas
  - libopenblas=0.3.18=openmp_h3351f45_0
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_1
  - libwebp=1.0.1=hd73b212_0
  - libxml2=2.9.10=h7cdb67c_3
  - llvm-openmp=12.0.1=hda6cdc1_1
  - lz4-c=1.9.2=h79c402e_3
  - matplotlib=2.2.3=py27h54f8f79_0
  - mmtf-python=1.0.2=py27_0
  - msgpack-python=0.6.1=py27h04f5b5a_1
  - ncurses=6.2=h0a44026_1
  - numpy=1.15.4=py27hbb3c62a_1002
  - olefile=0.46=py27_0
  - pillow=6.2.1=py27hb68e598_0
  - pip=19.3.1=py27_0
  - pyparsing=2.4.7=py_0
  - python=2.7.18=h47d645e_1
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - readline=8.0=h1de35cc_0
  - reportlab=3.5.26=py27hdea1bd8_0
  - setuptools=44.0.0=py27_0
  - singledispatch=3.4.0.3=py_1001
  - six=1.15.0=py_0
  - sqlite=3.33.0=hffcf06c_0
  - subprocess32=3.5.4=py27h1de35cc_0
  - tk=8.6.10=hb0a8c7a_0
  - - tornado=5.1.1=py27h1de35cc_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.4=h1990bb4_3
  - pip:
    - gclib==1.5.2
    - gdmodule==0.59
  ```
As you mentioned, `gdmodule` is not available through `conda`, so  I installed `gdmodule` by pip.

I tried 
```
conda env create -f environment.yml --name isosegmenter
```
but got this eorror:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - sqlite==3.36.0=hc218d9a_0
  - mkl-service==2.3.0=py27he904b0f_0
  - tk==8.6.11=h1ccaba5_0
  - mkl_random==1.1.0=py27hd6b4f25_0
  - xz==5.2.5=h7b6447c_0
  - libgfortran4==7.5.0=ha8ba4b0_17
  - libxcb==1.14=h7b6447c_0
  - libwebp==1.0.1=h8e7db2f_0
  - expat==2.4.1=h2531618_2
  - backports==1.0=pyhd3eb1b0_2
  - openssl==1.1.1l=h7f8727e_0
  - tornado==5.1.1=py27h7b6447c_0
  - backports.functools_lru_cache==1.6.4=pyhd3eb1b0_0
  - libuuid==1.0.3=h7f8727e_2
  - subprocess32==3.5.4=py27h7b6447c_0
  - ncurses==6.2=he6710b0_1
  - libffi==3.3=he6710b0_2
  - ca-certificates==2021.9.30=h06a4308_1
  - qt==5.9.7=h5867ecd_1
  - pcre==8.45=h295c915_0
  - libgd==2.3.2=hdd3ff0f_3
  - kiwisolver==1.1.0=py27he6710b0_0
  - zlib==1.2.11=h7b6447c_3
  - libgcc-ng==9.3.0=h5101ec6_17
  - numpy-base==1.16.6=py27hde5b4d6_0
  - libgfortran-ng==7.5.0=ha8ba4b0_17
  - libstdcxx-ng==9.3.0=hd4cf53a_17
  - icu==58.2=he6710b0_3
  - freetype==2.10.4=h5ab3b9f_0
  - certifi==2020.6.20=pyhd3eb1b0_3
  - pyparsing==2.4.7=pyhd3eb1b0_0
  - biopython==1.74=py27h7b6447c_0
  - pytz==2021.3=pyhd3eb1b0_0
  - python==2.7.18=ha1903f6_2
  - six==1.16.0=pyhd3eb1b0_0
  - python-dateutil==2.8.2=pyhd3eb1b0_0
  - readline==8.1=h27cfd23_0
  - gst-plugins-base==1.14.0=h8213a91_2
  - libgomp==9.3.0=h5101ec6_17
  - singledispatch==3.7.0=pyhd3eb1b0_1001
  - mkl_fft==1.0.15=py27ha843d7b_0
  - sip==4.19.8=py27hf484d3e_0
  - jpeg==9d=h7f8727e_0
  - intel-openmp==2021.3.0=h06a4308_3350
  - gstreamer==1.14.0=h28cd5cc_2
  - libtiff==4.1.0=h2733197_1
  - pillow==6.2.1=py27h34e0f95_0
  - fontconfig==2.13.1=h6c09931_0
  - _openmp_mutex==4.5=1_gnu
  - numpy==1.16.6=py27hbc911f0_0
  - lz4-c==1.9.3=h295c915_1
  - mkl==2020.2=256
  - wheel==0.37.0=pyhd3eb1b0_1
  - libxml2==2.9.12=h03d6c58_0
  - pyqt==5.9.2=py27h05f1152_2
  - zstd==1.4.9=haebb681_0
  - glib==2.69.1=h5202010_0
  - giflib==5.1.4=h14c3975_1
  - libpng==1.6.37=hbc83047_0
  - matplotlib==2.2.3=py27hb69df0a_0
  - dbus==1.13.18=hb2f20db_0
  ```
Since I am only interested in the intervals, can I workaround this `gcmodule` problem by disabling the plotting function? Thanks!

**Comment by bunop** [comment]
mmm, I see you work with MacOS and I'm quite sure that the conda compiled packages are different from linux ones, that's why you can't import my environment.

Regarding your workaround, yes it could work: comment out the `Graph` module and all it's occurrences in `isoSegmenter.py`. 

If you want to solve this issue, my suggestion is to install the `libgd` dependencies system wide (don't know if there's such package for MacOS or have sense to have it) and not in conda environment

I saw users solving issues with dependencies by using the *Docker* image I did, [here's the link](https://hub.docker.com/r/bunop/isosegmenter). 

Hope this helps

**Comment by houy10** [comment]
Thanks @bunop. I switched to linux, but am still having trouble with `gdmodule`:
```
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda



Downloading and Extracting Packages
futures-3.3.0        | 29 KB     | ###################################################### | 100%
subprocess32-3.5.4   | 51 KB     | ###################################################### | 100%
giflib-5.1.4         | 68 KB     | ###################################################### | 100%
ca-certificates-2021 | 116 KB    | ###################################################### | 100%
libstdcxx-ng-9.3.0   | 3.1 MB    | ###################################################### | 100%
libffi-3.3           | 50 KB     | ###################################################### | 100%
cycler-0.10.0        | 13 KB     | ###################################################### | 100%
olefile-0.46         | 49 KB     | ###################################################### | 100%
libgfortran-ng-7.5.0 | 22 KB     | ###################################################### | 100%
setuptools-44.0.0    | 512 KB    | ###################################################### | 100%
libuuid-1.0.3        | 17 KB     | ###################################################### | 100%
singledispatch-3.7.0 | 12 KB     | ###################################################### | 100%
python-2.7.18        | 9.8 MB    | ###################################################### | 100%
sip-4.19.8           | 275 KB    | ###################################################### | 100%
tornado-5.1.1        | 615 KB    | ###################################################### | 100%
jpeg-9d              | 232 KB    | ###################################################### | 100%
kiwisolver-1.1.0     | 84 KB     | ###################################################### | 100%
libxml2-2.9.12       | 1.2 MB    | ###################################################### | 100%
pyqt-5.9.2           | 4.3 MB    | ###################################################### | 100%
six-1.16.0           | 18 KB     | ###################################################### | 100%
libgomp-9.3.0        | 311 KB    | ###################################################### | 100%
libwebp-1.0.1        | 471 KB    | ###################################################### | 100%
backports_abc-0.5    | 10 KB     | ###################################################### | 100%
mkl_random-1.1.0     | 297 KB    | ###################################################### | 100%
libgcc-ng-9.3.0      | 4.8 MB    | ###################################################### | 100%
lz4-c-1.9.3          | 185 KB    | ###################################################### | 100%
readline-8.1         | 362 KB    | ###################################################### | 100%
numpy-base-1.16.6    | 3.5 MB    | ###################################################### | 100%
glib-2.69.1          | 1.7 MB    | ###################################################### | 100%
certifi-2020.6.20    | 155 KB    | ###################################################### | 100%
pip-19.3.1           | 1.7 MB    | ###################################################### | 100%
biopython-1.74       | 2.1 MB    | ###################################################### | 100%
matplotlib-2.2.3     | 4.8 MB    | ###################################################### | 100%
intel-openmp-2021.3. | 1.4 MB    | ###################################################### | 100%
openssl-1.1.1l       | 2.5 MB    | ###################################################### | 100%
libgd-2.3.2          | 230 KB    | ###################################################### | 100%
pytz-2021.3          | 171 KB    | ###################################################### | 100%
wheel-0.37.0         | 33 KB     | ###################################################### | 100%
functools32-3.2.3.2  | 23 KB     | ###################################################### | 100%
tk-8.6.11            | 3.0 MB    | ###################################################### | 100%
expat-2.4.1          | 168 KB    | ###################################################### | 100%
pillow-6.2.1         | 587 KB    | ###################################################### | 100%
sqlite-3.36.0        | 990 KB    | ###################################################### | 100%
backports-1.0        | 210 KB    | ###################################################### | 100%
mkl-service-2.3.0    | 217 KB    | ###################################################### | 100%
python-dateutil-2.8. | 233 KB    | ###################################################### | 100%
mkl_fft-1.0.15       | 146 KB    | ###################################################### | 100%
libgfortran4-7.5.0   | 995 KB    | ###################################################### | 100%
_openmp_mutex-4.5    | 22 KB     | ###################################################### | 100%
numpy-1.16.6         | 48 KB     | ###################################################### | 100%
pcre-8.45            | 207 KB    | ###################################################### | 100%
backports.functools_ | 9 KB      | ###################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
[‘/xxx/miniconda3/envs/isosegmenter/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/houy10/condaenv.wu_tv83o.requirements.txt']
Pip subprocess output:
Obtaining gclib from git+https://github.com/bunop/isoSegmenter.git#egg=gclib (from -r /home/houy10/condaenv.wu_tv83o.requirements.txt (line 1))
  Cloning https://github.com/bunop/isoSegmenter.git to ./src/gclib
Collecting gdmodule==0.59
  Downloading https://files.pythonhosted.org/packages/8d/83/7c7bf4186de4f368962d65f2556fd18e2816d13443a0c5ff2bc5e60ecf19/gdmodule-0.59.tar.gz

Pip subprocess error:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
  Running command git clone -q https://github.com/bunop/isoSegmenter.git /home/houy10/src/gclib
ERROR: Files/directories not found in /tmp/pip-install-TfGc3B/gdmodule/pip-egg-info

failed

CondaEnvException: Pip failed
```
I also tried Docker, but seems I don't have permission on the cluster:
```
ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=xfxhfrxvrh2fjfw4sbjg31gxt&shmsize=0&t=bunop%2Fisosegmenter&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by houy10** [comment]
@bunop Thank you for your help! I got it worked through docker =)

**Comment by YuanfengZhang** [comment]
COMMENT: Do not try to install it as what author said in README.md in the year of 2015, cuz it would be a horrible disaster to engage Python 2.7 if you have no experience in it. As any newest linux distribution does not include Python2.7.6, you have to comple zlib, manually install pyhon2.7.6, complie setuotools, compile pip, set $PATH... And compile openssl, maybe. Just use docker image and focus on your own bioinfomatic work.
